version: "3.8"

networks:
  some-net:
    driver: bridge

volumes:
  dbdata6:

services:
  knights.challenge-api:
    build:
      context: .
    command: sh -c "dotnet Knights.Challenge.API.dll"
    container_name: knights.challenge-api
    image: knights.challenge-api
    depends_on:
      - redis
      - mongodb
    links:
      - redis
      - mongodb
    ports:
      - "443:443"
      - "5009:5009"
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - some-net

  redis:
    image: 'redis'
    container_name: redis
    restart: always
    ports:
      - '6379:6379'
    networks:
      - some-net

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - '27017:27017'
    volumes:
      - dbdata6:/data/db
    networks:
      - some-net